
###get localhost 3000 cards
GET http://localhost:3000/api/cards 

###get localhost 3000 id
GET http://localhost:3000/api/cards/2



###post localhost 3000
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "text": "What is Node.js?",
    "author": "Max Mustermann"
}

###put localhost 3000
PUT http://localhost:3000/api/cards/1234abc
Content-Type: application/json

{
    "text": "Max Mustermann"
}

###Patch localhost 3000
PATCH http://localhost:3000/api/cards


###Delete localhost 3000
DELETE http://localhost:3000/api/cards